language: ruby
sudo: false
dist: trusty
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: "ruby-head"
    - rvm: "jruby-head"
addons:
  apt:
    packages:
      - graphviz